// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191028183209_Country")]
    partial class Country
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Travel.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityName");

                    b.Property<int>("CountryId");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 3,
                            CityName = "Los Angelos",
                            CountryId = 1
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Paris",
                            CountryId = 2
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Venice",
                            CountryId = 3
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Hong Kong",
                            CountryId = 4
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "London",
                            CountryId = 5
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Delhi",
                            CountryId = 6
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Nairobi",
                            CountryId = 7
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Bali",
                            CountryId = 8
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Brasilia",
                            CountryId = 9
                        },
                        new
                        {
                            CityId = 12,
                            CityName = "Portland",
                            CountryId = 1
                        });
                });

            modelBuilder.Entity("Travel.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryName");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "Hong Kong"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryName = "England"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryId = 8,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryId = 9,
                            CountryName = "Brasil"
                        });
                });

            modelBuilder.Entity("Travel.Models.City", b =>
                {
                    b.HasOne("Travel.Models.Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
