// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191028172845_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Travel.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityName");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 3,
                            CityName = "Los Angelos"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Paris"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Venice"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Hong Kong"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "London"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Delhi"
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Nairobi"
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Bali"
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Brasilia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
